### ISSUE TITLE
Update ~ 2016-04-15 ~ Fgx FlightPath R2

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#1]
![image](https://cloud.githubusercontent.com/assets/547626/14579443/67b31c2a-035e-11e6-92b9-452414cc8240.png)

_FGx FlightPath R2_

---

@geoffmcl @pedromorgan 

I'd like to start chatting using GitHub issues. Is this OK with you?

GitHub issues have tags and can be closed and use Markdown and do all sorts of other cool things

---
### Features
- Reads flightpath data from a CSV file
- Creates a spline from the data
- Simulates the motion of an aircraft following the spline path
### Issues
- LookAt next point has gimbal lock issues
### Naming

Keeping the same naming convention for time being on my side because I think it's nice for a newcomers to be able to look at a title and get an idea as to what the script does.

Feel free to fork and rename. ;-)
### Remarks

Can we talk about what would be the ideal data set?

To me, it might be

julian date, latitude, longitude, altitude, roll, pitch, yaw followed by details such as landing gear, flaps and any text notes as well.

Captured every second or sub-second? ASCII or Binary?

Does Flightgear have the ability to capture and export data like this? Or does the Crossfeed data contain these variables?

BTW, no need for speed or bearing etc as these can be calculated from the given data.

If you can send me any data like this, then I can make it fly. ;-)

**Comment by geoffmcl** [comment]
@theo-armour have no problem using `issues` in a repo... and yes its markdown, and other options are all ok... it is for sure one of the norms I handle...

I added a new rough [flightpath-r3d](http://fgx.github.io/sandbox/flightpath/fgx-flightpath-r3.html). It uses my modified `flightpath-03.csv`... so I got to understand the z,x,y coordinates... it seems the speed is based on the space between 3d points... but need to experiment more... and wish there was no pause between the land and takeoff...

**Real Data set**

A `real` Flightgear (FG) flight, flying `fgfs`, can be **recorded**. This can be done `many` ways, and with that, many options of what the `set` consists of -

 A: Connecting FG to multiplayer, a fgms server instance, say mpserver01, mpserver14, ...
    - 1. As you mention, [Crossfeed](http://crossfeed.freeflightsim.org/flights.json) (CF), can be used to get a position each second.
    - 2. After the flight is completed, get the Google Earth [klm](http://mpserver15.flightgear.org/modules/fgtracker/?FUNCT=KML&FLIGHTID=6588208) data from FG Tracker [API](http://mpserver15.flightgear.org/modules/content/index.php?id=4)
 B: FG has many [i/o](http://wiki.flightgear.org/Generic_protocol) possibilities, which can output a set of properties, say at 1-5Hz

Now I have not yet done A:1, nor B:, but will try to get to those...

And the A:2 is a flight from LEBL to LEIG - Cessna 172P 2016-04-08 01:25:39+08 ---- 2016-04-08 02:04:10+08 LEIG 00:38:31 00:31:20 232 wpts... 

That is I have not yet done the desired circuit and tracked it... but will get to that... when I prefect getting the best, safe flight path... still WIP... piloting in new hilly terrain is **not** easy, until you get to fully know the lay of the land...

Now this kml consists of 232 `Placemarks`, taken each 10 seconds. It includes a `<Point><coordinates>lon,lat,alt_m</coordinates></Point>`, and has an order number and timestamp `<name>#5:2016-04-08 01:26:36+08</name>`, etc, etc, ... loads fine in Google Earth...

Now I have my `published` extraction perl script, [kml2xg.pl](https://github.com/geoffmcl/scripts/blob/master/kml2xg.pl), which gives me a simple cvs/xg list of wpts - lon,lat,alt_m

But as indicated, at this time I only have the full LEBL to LEIG flight `recorded`, but will also to the same for the LEIG PPL circuit I really want...

And still to explore the other FG `recording` options. Using B: we could certainly include roll, ... -

julian date, latitude, longitude, altitude, roll, pitch, yaw, gear, flaps, ...

Will come back shortly with something... ;=))

**Other Issues**
- The display to include the 3D generated terrain
- The model aircraft to be the c172p
- A follow view mode where the camera is out the front of the model
- minor: cvs must not end in a newline - protect against a v(0,0,0) last point

Should I open individual issues for each of these, and maybe others? Or we deal here for a while...

As stated, this is **looking** very good... thanks...

**Comment by theo-armour** [comment]
@geoffmcl 

**>>  and wish there was no pause between the land and takeoff...**

your wish list = my command line

can be done in two ways: 

1.uncommented line in animate to force instant jump
or
2. Edit CSV file to leave gap between start and end point.

Currently #2 is applied.

script [re-titled to 3.1](http://fgx.github.io/sandbox/flightpath/) and read me updated

**>> Should I open individual issues for each of these, and maybe others? Or we deal here for a while...**

I have added your items to the [read me](http://fgx.github.io/sandbox/flightpath/#readme.md)

**Real Data Set**

Can I see a sample or two of 5HZ most _raw data_, please?

BTW, I consider KML files to be a good lesson in obfuscation, but nevermind. ;-)

---

More later...

**Comment by geoffmcl** [comment]
@theo-armour one thing leads to another...

It seem my request for `no pause`, should be amended to a much more complex...

If the beginning, start at zero, accellerate, and takeoff..

However, on landing, skip the first few points, but slow down, and then
accellerate to takeoff speed... join the previous... maybe quite difficult
to implement... 

Sort of skip an overlap of spines... rejoin at takeoff... with speed... 
maybe need meta data to delineate... or something... but, really thanks what 
now seems like a **no pause**... down one,,,

But that is minor... to getting a real **circuit** to be flown...

After many, **many** circuits, and circuits in the c172p...

I have now **decided** on a 2600 AMSL left circuit... and have flown it several 
times... it involves instructions like, turn left at the castle on the hill,
to about 70 degrees, follow up the valleys, until over the escarpment, then pick 
up the A-2, do a left, and re-do the tutorial for a runway 17 approach...

So I am getting closer to generating such a flight, recorded by FG Tracker... hang in there...

> KML files to be a good lesson in obfuscation

Sorry, not sure what this means... that the true data is deep in a structure... or what? Wow, like most XML implementation, you really need to know the `structure` to do a parse... While xml, as ascii text, offers a great way for information exchange, the problem is always knowing the details of the **structure** ...

No, we should accept **every** output possible, so long as we can read the **results**, and generate a form we prefer...

The simple form here, cvs,xg,... is `lon,lat,alt,...` ...

Sometimes, as a veteran pilot, thousands of hours PIC, or as a baby PPL with, what, at most 60 hours PIC, what qualifies a person as an `instructor` on such matters? Need to read the appropriate instructors handbook, for that...

For sure this will be my **gut feeling** of choosing the **correct** 2600 foot, left, circuit of LEIG is as above, and is based on all that I know, or have read to this point, **but** I can be real wrong...

I will have an KML file, hopefully shortly ;==))

**Comment by geoffmcl** [comment]
Oops, where did my reply land?

**Comment by geoffmcl** [comment]
ok, seems the right place... why do I not see this...

**Comment by theo-armour** [comment]
@geoffmcl 

> > Oops, where did my reply land?

I believe right where it was meant to land.

> > It seem my request for no pause, should be amended to a much more complex...
> > If the beginning, start at zero, accelerate, and takeoff..

My guess: Once we have some 'real' data - not the data we are inventing on the fly - then most of these issues should take care of themselves

> > No, we should accept every output possible, so long as we can read the results, and generate a form we prefer...

Bingo!

> > The simple form here, cvs,xg,... is lon,lat,alt,... ...

A very good starting point. Please start with data in formats like this - for me to get going quickly. Pretty please.
