### ISSUE TITLE
2016-07-10 ~ VNLK Flightpath R1

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#27]
![image](https://cloud.githubusercontent.com/assets/547626/16719300/8b485714-46dd-11e6-8e7b-e47d29ea9d4d.png)

@fgx/owners 

Now, can we get the terrain and the flight path in the right places and at the right scale

And we want to be able to zoom closer and not get all pixelated.

Here the interesting thing:

This script handles one flight path for one airport.

It may be a lot easier to build lots of individual scripts like this than to build a big script that handles many airports and many paths.
### 2016-07-10 ~ R1
- First commit
- Add Read Me

**Comment by geoffmcl** [comment]
Hi Theo,

Re: https://github.com/fgx/fgx.github.io/issues/27

Yay, we have a new `track`... wish you had chosen 'VNLK-01-cooked.csv', or
Jasin's first VNLK flight,
`6-25-2016-1-cooked.csv`, or a later `6-27-2016-1-cooked.csv`, South, just
added... but no problem...

The main thing I see is the mis-matched elevations - that is the elevation
of the track, and thus its bounding box, is **too** high... like in
VNLK-02, one end is the takeoff from the VNLK runway, so should touch the
ground...

In most of the other `tracks` they should begin with a **takeoff**, and end
with a **landing**, so both ends must touch the terrain... and conversely,
the track should nver pass `through` the terrain...

I looked at vnlk-flightpath-r1.html, but can no see axactly where this
altitude is set...

This first track,
http://fgx.github.io/sandbox/flightpath/fgx-flightpath-r13.html, does touch
the terrain,  so what is different? it seems `accurate` with regard to
altitude...

> It may be a lot easier to build lots of individual scripts like this ...

That I can understand, but that would be **sad** ;=((

I can see the `scene` now requires an elevation file,
elevations_27.6730_86.7171_z12_t5_250x250_vnlk-both-paths.txt, in this
case...

That threw me for a while, since it seemed the position `_27.6730_86.7171`
was **outside** the tile, but maybe I did some wrong maths!

We are for sure talking about the tile
http://b.tile.openstreetmap.org/12/3034/1719.png

Been fiddling with generating `contours`, and generated this -
 http://geoffair.org/tmp/elev-tile-12.3034.1719.png
using your elevations... lots of fun... still a WIP...

Note the little `06`, bottom right, with pink paralell lines, being the
VNLK runway... adding that type of known `position` helps me orientate the
scene in my mind...

So this new `track` process seems to be coming clearer -
1. Fly the flight, gen the cooked csv
2. Review the limits, plus a fudge, and generate `elevations` txt
3. copy `r1` to 'flight-20160711.html', and modify two inputs...

And if always just the two file inputs (csv/txt), maybe a general version
would accept parameters to set these two, and hope that they two `match`...
like `gen.html?csv=123.csv&elev=123.txt&z=12`... or something...

Anyway, the first thing seemed to be to get the relative component
`elevations` fixed...

But great, as usual, and thanks...

**Comment by theo-armour** [comment]
@geoffmcl 

Sorry. I should have explained that this was a work in progress. I did a bit more today but it's still far from accurate. I think the best thing you could say about it is that the flight path and the terrain are 'near' each other and that's about it.

The interesting script is the one that obtains the elevation data:

[Elevations Get](http://jaanga.github.io/cookbook-threejs/examples/google-api/elevations-get/)

There are two ways of initiating the map. 

The first way is to type in almost anything in the address input box. Google will try and identify the place and once you accept the latitude and longitude of here and the map is updated.

Click the 'get elevations'. A 3D landscape should appear in sends - if you stick with 30 samples per side.
500 per side takes about an hour.

The second way is to load a flight path file. Once the file is loaded and the menu is updated you can click to 'go there' button or the redraw button. You can even load all thee VNLK flight paths at the same time on the same map.

The user interface is too complicated. And there is too much data. But these are all tools in the effort to get the data faster and more accurately - and all will be streamlined and more data sources added as time goes on.
