### ISSUE TITLE
2016-07-13 ~ YGIL Flightpath R1

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#29]
![image](https://cloud.githubusercontent.com/assets/547626/16812212/f862a782-48e0-11e6-848f-47c001750524.png)

@geoffmcl 
### 2016-07-13 ~ R1
-  flight path is in correct position - but the landscape is not

**Comment by geoffmcl** [comment]
Hi Theo,

Re: https://github.com/fgx/fgx.github.io/issues/29

http://fgx.github.io/sandbox/flightpaths/ygil/ygil-flightpath-r1.html

> flight path is in correct position - but the landscape is not

Again the x/longitude seems correctly aligned, but the z/latitude, is a few miles different ;=)) 

That nasty `lat` again! I could probably guess this in degrees, or meters, if that would help...

That is the lowest point in the 'track', is presently a few miles north of the short gray runway I used for takeoff and landing... that crosses the longer `brown` runway...

And even though YGIL is **flat**, there are some higher terrain, where I would expect the bottom bbox - the yellow - to intersect, and even go below the actual terrain elevation...

That is when I swing it around and get a side on view, I can see that yellow bottom bbox seems to just touch the **highest** point in the terrain... ie its y/altitude is **too** high, or the terrain needs to be **raised** up...

If both of these problems can be fixed by moving the `terrain`, ie the (x,y,z) position of the elevations array, then, yes the `landscape` is **wrong**...

And that makes sense, since the track is already wsg84 lon,lat,alt, ie exact coordinates - they can **not** be moved, or adjusted - they represent the only truth...

On the other hand, it is you to calculates, from parsing the elevations file name, the positioning of the elevation array, and there seems a problem with the **z/lat** and **y/alt** assigned... Will see if I can understand what you presently do about this, and try to `suggest` something... but sure you will get there quicker...

Anyway, again thanks for the nice view of one of my `home` towns... where I did my very first flying...

Regards,
Geoff.

**Comment by theo-armour** [comment]
@geoffmcl 

All good observations

The issue seem to be working them selves out, so I would not spend much time om this - unless I as for hr;p.

Things that would be good:
- Lots more flight paths
- Looking into industry standards for flight path files
  - Note that Wikipedia suggests as a simple KML format: https://en.wikipedia.org/wiki/Keyhole_Markup_Language
  - Or perhaps just the Crossfeed format
- Investigating [Elevations Get](http://jaanga.github.io/cookbook-threejs/examples/google-api/elevations-get/elevations-get-r2.html)
  - I think this could end u being a very useful tool for many sectors
  - like 3D print your mountain hike

**Comment by geoffmcl** [comment]
Hi Theo,

> Lots more flight paths

This is sort of a chicken and egg problem...

Yes, I could advertise, people should record a FGFS flight, and see it
displayed in a 3D playback... par Theo...

That might yield no takers, or hundreds of requests...

I will try to add my own flights, as I can, as I, and Jasin, have done...

But the current default `playback` xml produces a **big** csv file... and
we need to massage it, to get a **coooked** csv...

Now there seems some more steps - download an `elevations` file, to match
this `flights` limit...

> industry standards for flight path files

As discussed, in reading the big, easy to make, default, generate, anytime
you fly FGFS, a `playback.csv`, and presently outputting the **cooked**
version, it can also output `kml`... as mentioned, presently too verbose,
but could be trimmed... I will try to add an topion for this...

Or **more** formats, once defined...

But in a way the present **cooked** csv is also quite a `standard`...

> Investigating Elevations Get

https://jaanga.github.io/cookbook-threejs/examples/google-api/elevations-get/elevations-get-r2.html

Yes, it **is** a useful tool, probably in lots of cases...

Being able to load, and apply a 3D elevation **mesh** to any 2D map display
is **FANTASTIC**!!!

It opens a world of possibilities, no doubt...

Subject only to Google API useage...

> 3D track display

But there has to be some co-ordination between the two(2) files required
for a display -
1. The track - wsg-84 lat,lon,alt,+++ - the facts!
2. The elevations - flat file, covering the `track`, usually more than...

With these two(2) files, boink up a 3D display, with a few hundred lines of
javascript code... absolutely **BEAUTIFUL** ;=))

Again, just really **observations** ;=))

Regards,
Geoff.

**Comment by theo-armour** [comment]
all good/interesting observations

KLM

typical file from GPS device with no altimeter;

https://github.com/jaanga/jaanga.github.io/blob/master/demo/cba/elevations/Snow_Mountain_Actual.kml

Not too bad really.

I will be using KML files a lot to display my daughter Cynthia mountain hikes.

If for no other reason than Google Maps APIS can read them from a URL

https://developers.google.com/maps/documentation/javascript/examples/layer-kml

so worth looking into.

though I love straight simple CSV files that can fail half way and still work. ;-)

**Comment by geoffmcl** [comment]
Hi Theo,

Yes, reviewing that kml -

https://github.com/jaanga/jaanga.github.io/blob/master/demo/cba/elevations/Snow_Mountain_Actual.kml

As you point out, it uses an interesting feature - no altitude given -
using -

```
    <LineString>
        <altitudeMode>clampToGround</altitudeMode>
```

But here, we want a flightpath, where **altitude** is an important part of
the `track` information...

As mentioned, I am sure I can trim the kml generated from the raw playback
csv, and this certainly remains an otpion to consider...

But I too love the straight **cooked** csv, that says everything, including
model orientation...

And I earlier used `wobbly` for the orientation... however, as I look
deeper, some of those `wobbles` actually point out my **bad** flying... so
they may be correct...

Well, a tiny, tiny thing, and that is the point of rotation of the model...

When landing, my flair, just on arrival, put the model tail underground...
but like I say, that is just changing the point of the pitch rotation... or
maybe the choice of the center of the model that is actually flying the
track... small adjustments to be perfect...

Regards,
Geoff.

**Comment by theo-armour** [comment]
> tail underground

Don't forget. The current scale of the model of a b52 not a c172! ;-)

**Comment by geoffmcl** [comment]
Hi Theo,

Re: https://github.com/fgx/fgx.github.io/issues/29

> Lots more flight paths

Have now added two more - 
1. VHSK - Short, 500 foot circuit of Sek Kong
2. KGCN - Short trip over the Grand Canyon

In both cases now include a modified, simplified, KML, which works fine in Google Earth... check em out...

For VHSK I started to go down the road, and fetched 2 elevation files... was headed towards adding the HTML, but then saw need to supply an index.html and the actual `flight` html, and ran out of time tonight...

Used the [Get Elevations r2](https://jaanga.github.io/cookbook-threejs/examples/google-api/elevations-get/elevations-get-r2.html)... could not get the `r3` to set the download output file name correctly... 

And in both cases, appears no way to close the new `view` on download completion...

Have fun ;=))

Regards,
Geoff.

**Comment by theo-armour** [comment]
@geoffmcl

Yay! Thanks.

Will look and reply later today

https://jaanga.github.io/cookbook-threejs/examples/google-api/elevations-get/elevations-get-r3.html

https://jaanga.github.io/cookbook-threejs/examples/google-api/elevations-get/index,html
points
to the above - but you may need to do a hard reload in order to clear the
cache.

R3 allow you to click to a new location

**Comment by theo-armour** [comment]
![image](https://cloud.githubusercontent.com/assets/547626/17003914/174067ec-4e87-11e6-918c-44ae97220c2c.png)

@fgx/owners 

Positions looking good

http://fgx.github.io/sandbox/flightpaths/ygil/ygil-flightpath-r4.html

**Comment by theo-armour** [comment]
http://fgx.github.io/sandbox/flightpaths/ygil/ygil-flightpath-r5.html

**Comment by pedromorgan** [comment]
COOL.. amazing .. u got me exoted again
