### ISSUE TITLE
Use of Images in GitHub Issues

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#32]
@fgx/owners 

In this message

https://groups.google.com/forum/#!topic/fgx-project/5-JRYBpakxY

Geoff: you raise a lot of interesting questions regarding the use of images in GitHub issues. All your points are valid and worth addressing.

Note: I won't be able to address all the points in one message. And none of the messages in this thread will have images. ;-)

From my point of view, FGx is nearly dead:

https://github.com/fgx/fgx.github.io/graphs/traffic

There's not much happening here. And nobody does any promoting of what's here elsewhere in FG circles.

It would be easy to do what I am doing elsewhere, but it is nice to have a focus om aspects of flying and access to Pete and Geoff's experience.

Also I kind of suck at doing promoting and blogging and the like.

So the idea came to me to use the things I normally do like writing to change logs, explaining things as a way of creating a marketing or promoting things without too much effort.

You can see some of the results here:

[Theo Armour](https://theo-armour.github.io/github-api-users-explorer-r3.html)
[Geoff McLane](https://theo-armour.github.io/github-api-users-explorer-r3.html#GeoffMcl#1)
[Pedro Morgan](https://theo-armour.github.io/github-api-users-explorer-r3.html#pedromorgan#1)

I am in the process of building a similar work for GitHub organizations. It would be great to build something like this for FGx

A different way of promoting what an organization is doing is available here;

https://ladybug-analysis-tools.github.io/ladybug-web/ 

Scroll down and you will see lots of use of 3D.

And this is the thing: If you want to get people interested in 3D and animation and interaction, then showing text is a turn off.  For good things to happen there has to be a regular progression of fresh graphics.

I'm not saying what I'm doing is the right way. I'm just investigating ways of being able to code faster miles an hour and in the process create its own promotion.

I am loving GitHub issues because:
- Pasting in images just work
- Posts can be edited
- Markdown is supported
- Emailing is taken care of
- # and @ work
- Emojis work
- You can set up groups 
- It's so close to the code it's discussing - much closer than Google Groups
- and much more

But enough for now. More tomorrow.

I may not be doing things right, but the intention is to get FGx flying again - and hopefully with an auto-pilot for doing the marketing.

And, using one of my favorite Geoff expressions,

Bye for now...

Theo

**Comment by geoffmcl** [comment]
Hi Theo,

Re: https://github.com/fgx/fgx.github.io/issues/32
Re: https://groups.google.com/forum/#!topic/fgx-project/5-JRYBpakxY

> you raise a lot of interesting questions... and
> won't be able to address all the points in one message

Ok, no problem... So, my first question is did you address **any** in the above reply?

It seems you raised some **other** issues, like -

> ..., FGx is nearly dead:

Well, as discussed before, the main project here, the FGx Flightgear Launcher (FGx), is probably moribund...

First, it was never fully ported to Qt5, and now faces a Qt5 --launcher built into FGFS itself, making the building of this **better** mouse trap!, externally, not very appealing...

But then, mainly grace a you, it started to get into 3D rendering... started collecting 3D models, and showing them on a 3D map/terrain display... the overview page - http://fgx.github.io/ - shows each of those, going back over quite a number of years...

To me, this reached a peek with - http://fgx.github.io/sandbox/flightpath/fgx-flightpath-r13.html - and only very recently started to get back to this, with things correctly placed... still no model... new elevations API to learn...

And until, as discussed in `The Future - Dream`, to me there is nothing really to **promote** with this yet... it is still a WIP... we need to offer a 3D flight playback service, or something...

> ... a way of creating a marketing or promoting things without too much effort.

Yes, I can **see** what you are doing, and only suggested large embedded static images in just about every **issue** does not help with this... IMO...

Your creation of a special page - https://ladybug-analysis-tools.github.io/ladybug-web/ - with all the projects created and shown in a single HTML pages, if you scroll down enough, and are patient enough to wait for each 'sub-project' to load, is **GREAT**...

This is absolutely **perfect** for the first time user - a quick overview, 1-by-1, just by scrolling -  certainly beats the menu approach in - http://fgx.github.io/ - where you have to click each to see all - to see if you have any interest in the 'project', and will **watch** its progress... maybe participate...

But par contra is absolutely **bad** for the repeat user, who I am sure would like the simpler verbal only `menu` approach, that loads instantly, simply as a quick link to some sub-project you are following...

But I do not think that has anything to do with adding a static image to each **issue**, which, as stated, I believe is very distracting to such a repeat user...  

And, for instance, leaving a **bad** image like - https://github.com/fgx/fgx.github.io/issues/29#issue-165372016 - now that we have the great - https://github.com/fgx/fgx.github.io/issues/29#issuecomment-234091061 - does not seem a good promotional thing... 

Yes, it shows progress, but showing failures and calling it promotion do not seem to fit too well together... 

Yes, there is nothing wrong with adding the latest, and best image!, to say the bottom of a README.md, or a web pages...

So, remember this is just about the `use of images in GitHub issues`! That's all... there **are** other good places to use these images, but prefer it like the `ladybug-web`, where it is the actual, not some static nothing...

Re: **Posts can be edited**

Yes, they can, but take care with that... While I do not know exactly, an email is **only** generated when the issue is first posted. No new email is sent on edits of the comment!

If you have a known user, that perhaps does not use the **Preview** button; that can have second, third,  thoughts; can add, remove, or adjust points, text, etc, then it is bad news to reply directly to the email... you can end up jumping on something said, that has be subsequently edited... making for a very messy conversation...

And yes, the fact that - pasting an image just works - is great! There are times where a picture can explain the issue much better - absolutely true... and should be used...

So I think I am just commenting on what I felt was an over-use, even a big distraction...

I want to be able to scroll back up the comments made, to remind myself what has already been said, and not have to scroll up over some big fat static images... 

That's all...

Regards,
Geoff.

**Comment by theo-armour** [comment]
@geoffmcl 

> Ok, no problem... So, my first question is did you address any in the above reply?

I did not. ;-)

I first wanted to point out that the issue of images in issues on Github has a number of issues.

I am responding to 'moribund' bits here:

#34 Is FGx Moribund? If so, what to do?

> So, remember this is just about the use of images in GitHub issues! That's all...

The issues with images all have the tag 'Status Update'.

Their intention is to act sort of like a blog post. Issues with this tag should inform members of new activity. And since everything in FGx relates to 3D one way or another, it really helps to have an image.

On the other hand scrolling through the images is a pain.

The are several possible solutions.

GitHub organizations allow you to create  a variety of teams - each of which can have its own set of members.

So one course of action might be to create an FGx/Updates team and then set things up so that only the members of that team get sent notifications.

The other possibility is to understand and agree that 'Status Update' messages are just that and should not be used for general commenting.

Whenever I sent out an update. I suppose I could add a second issue just for commenting - but that seems like overkill.

Would it not make sense for anybody that has a comment about one of the updates, to open up a new text only issue ? And the new issue should have any tag besides a 'status update tag. ;-)

**Comment by pedromorgan** [comment]
Can I suggest we move over to FreeFlightSim instead.. (and redirect)

FSX created by Gral. was "flightgear" and os "x".. but FGX is too "wide a term" so dont work...

Just a suggestion.. mainly because I (and @geoffmcl  soon or anyone trusted) can have control of DNS and do things.. and move on...

**Comment by theo-armour** [comment]
@fgx/owners 

## FGx

I always thought the x is was for 'extras; or 'effects' as in 'fx'

## Move to freeFlightSim

Seems like a reasonable idea. Nobody know what 'fgx' is, but they would understand free - flight - sim.

**Comment by geoffmcl** [comment]
Hi Pete... thanks for the suggestion to use your `FreeFlightSim` domain... this is very kind, and generous... you already do a lot - fgms server 14, json/xml crossfeed, api docs per DNS - `fgms.`, `fgx.`, access, etc... 

But I do not understand what **move over to** means in this context... move what exactly? emails? issues? repos?... what?

Yes, after Yves (Gral) dropped away, I came to think of `FGx`, like Theo, as `FlightGear eXtra`, and now quite like this moniker/label/brand/3 letter code/shortcut/... We really need to correct a lot of README/Wiki/etc... text to reflect this...

While - `free-flight-sim` - may seem more verbally understandable, that, to me, loses the important association with FG (FlightGear)... there is more than **one** `free-flight-sim`... but also agree `FreeFlightSim.org` is a great domain name...

And while this started as a discussion of adding embedded images into issues, which I have no real problems with, just questioned the reasoning, and usefulness... it is also about our `group` identities...

As Theo enumerated above there are **LOTS** of good things about this GitHub **issues** system... aside from it being close to the actual code, I particularly like the fact that it auto-emails to all subscribers/owners, and am  getting to **like!** `markdown`...

Love that a Google query - flightgear FGX - yields lots of important links, including this fgx.github.io...

So before any **move**, like I say, whatever that exactly means, all these things should be considered...

Simply, I have no problem with how we are progressing now... as FGx... but again, thanks Pete...

Just my 2 cents...

Regards,
Geoff.

**Comment by theo-armour** [comment]
@geoffmcl 

I think Pete is referring to:

https://github.com/freeflightsim as a file repo

and freeFlightSim.org for when a server is required.
