### ISSUE TITLE
2016-07-21 ~ LEIG FlightPath R1 ~ Many errors

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#33]
![image](https://cloud.githubusercontent.com/assets/547626/17041870/1d68ae5e-4f5e-11e6-9109-46455b125740.png)

@fgx/owners 
### 2016-07-21 ~ R1
- FlightPath now in flight-path-r2.js
- Aircraft now in aircraft-r1.js
- First commit
- Add Read Me

**Comment by geoffmcl** [comment]
@theo-armour - many errors... well yeah...

The lon and alt look fine, and again the `lat` seems off...

And of course there is the `inverted` model orientation...

But otherwise, quite reasonable for a first - with model - commit... 

It seems some adjustment needed for the new flightpath and model `.js`? 

Who, how, were these generated?

But YEAH, we have a model flying the `track`... great... thanks...

Still reading the next six plus messages... 

Regards,
Geoff.

**Comment by pedromorgan** [comment]
Geoff can I make a suggestion we shut down fgx.goups google etc..

As @theo pointed out its in GH atmo..
and move that way..

Am behinh @theo cos i dont want @theo to be punched in the face like some
forum members do..
Instead be critical and an credability of.. right.. this is reall cool ;-)))

**Comment by theo-armour** [comment]
I don't think the FGx Google Group actually needs to be 'shut down'. It can just sit there.

But I do think that GitHub issues are the way to go forward - if nothing else because they are so much closer to the code.
