### ISSUE TITLE
2016-07-29 ~ Landscapes are cool

### ISSUE THREAD

**Issue by theo-armour** [fgx/fgx.github.io#36]
<img src=https://cloud.githubusercontent.com/assets/547626/17268348/8679eafa-55dc-11e6-8d67-62a0a77d9190.png width="600" height="300" >
_VNLK zoomed out_

<img src=https://cloud.githubusercontent.com/assets/547626/17268368/51fbb87a-55dd-11e6-877e-d8f3cfaceb2e.png width="600" height="300" >

_VNLK zoomed in_

@fgx/owners 

If images are inserted to issues as IMG tags instead of Markdown format does this help @geoffmcl with his larges images in emails issues?

In any case, you will notice that the terrain is chill.

The links
### [YGIL](http://fgx.github.io/sandbox/flightpaths/ygil/ygil-flightpath-r5.html)

In all cases, please update 'Map zoom level' to 14 or 15 in order to generate a higher quality overlay.

And, in most cases, you will have to reduce the vertical scale.

And, sorry Pete, you can still fly underground.

There's a ton of issues with each. No need to mention any of the many issues.

Just enjoy looking at the terrain!

**Comment by geoffmcl** [comment]
Hi Theo,

If this is only about **viewing** terrain... then **yeah**, 
this is **cool** ;=))

Then forget the rest...

If this is about **viewing** my last flight, recorded by FGFS playback 
protocol, in 3D, without re-running FGFS, or using Google Earth kml, 
then this does **not** yet do that! 

Well, not without a lot of hoop jumping... ;=))

How can we simplify this?

> There's a ton of issues with each. No need to mention any of 
> the many issues.

Wow, ok, aside from the fact that it misses **my** aim, to display a `track`,
be it from a pre-recorded FGFS session, or hopefully say live, from say
current crossfeed, then these are **perfect**... what else can I say?

A simple 3D terrain view... centralised on a pre-recorded, **cooked** csv
track file... **great**... **yahoo**...

So eagerly await **self** improvements... given time, interest, etc...

Re: images in emails/issues

Theo, I have **no problem** with you adding images to emails/issues... even 
suggested sometimes it is good, and necessary... but to imbed, either as markdown 
or img tags, in each new `issue`, does not seem neccessary... especially since 
usually the link(s) can show a **live** example... but really - *\* no problem *\* - 
you like it... so be it...

I can live with anything others produce... if it is helpful... to the cause...
and sorry I may offer ideas on how to improve that... but they can be rejected... 
no problem... no argument required...

So what I want is a playback, in 3D, of my last flight... pure and simple...

Coincidentally, I tried the relatively new `Phi` user http interface to FGFS... 
it has a moving 2D OSM map to plot your track... I think that could be in 3D, 
with all that, that entails... dreams...

We do **not** seem anywhere near that yet... viewing the **terrain** is
only the first step... no matter how **cool** it looks...

Regards,
Geoff.

**Comment by theo-armour** [comment]
@geoffmcl 

Sorry for being confusing.

The goal to replay your last flight in 3D is still very much the goal.

I was just trying to inform you that the issues with the flight paths and animations are still huge and not worth commenting on - just for the time being though.

**Comment by theo-armour** [comment]
@fgx/owners 

## [Elevations View](https://jaanga.github.io/terrain3/elevations/elevations-view/)

This is the latest underpinnings for creating the 3D flightpaths.

It will have CSV and KLM support very soon.

Any thought or comments would be appreciated.

I hope to start send links out to a wider audience as and when its stable

Update: just checking the link. It may need a reload in order to run the very first time. ;-(
